
//USER ACTIONS
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_APPROVED = "LOGIN_APPROVED";
export const LOGIN_DENIED = "LOGIN_DENIED";
export const LOGOUT = "LOGOUT";
export const CHECK_LOGIN_STATUS = "CHECK_LOGIN_STATUS";

//POST ACTIONS
export const GET_POSTS = "GET_POSTS";
export const DISPLAY_POSTS = "DISPLAY_POSTS";
export const UPDATE = "UPDATE";

//GLOBAL ACTIONS
export const FAILED_REQUEST = "FAILED_REQUEST";
export const REQUEST = "REQUEST";